apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
    spec:
      serviceAccountName: recipes
      initContainers:
        - name: init-recipes
          image: vabene1111/recipes
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: recipes-secret
          env:
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: postgresql.platform.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: recipes
            - name: POSTGRES_DB
              value: recipes
          volumeMounts:
            - mountPath: /opt/recipes/mediafiles
              name: media
              subPath: files
            - mountPath: /opt/recipes/staticfiles
              name: static
              subPath: files
      containers:
        - name: recipes-nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /media
              name: media
              subPath: files
            - mountPath: /static
              name: static
              subPath: files
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx-config
              readOnly: true

        - name: recipes
          image: vabene1111/recipes
          imagePullPolicy: IfNotPresent
          command:
            - /opt/recipes/venv/bin/gunicorn
            - -b
            - :8080
            - --access-logfile
            - "-"
            - --error-logfile
            - "-"
            - --log-level
            - INFO
            - recipes.wsgi
          ports:
            - containerPort: 8080
              name: gunicorn
          envFrom:
            - secretRef:
                name: recipes-secret
          env:
            - name: DEBUG
              value: "0"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: GUNICORN_MEDIA
              value: "0"
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: postgresql.platform.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: recipes
            - name: POSTGRES_DB
              value: recipes
          securityContext:
            runAsUser: 65534
          volumeMounts:
            - mountPath: /opt/recipes/mediafiles
              name: media
              subPath: files
            - mountPath: /opt/recipes/staticfiles
              name: static
              subPath: files
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: recipes-media
        - name: static
          persistentVolumeClaim:
            claimName: recipes-static
        - name: nginx-config
          configMap:
            name: recipes-nginx-config
