apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret
  namespace: n8n

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao

  target:
    name: n8n-secret
    creationPolicy: Owner

  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: apps/n8n
        property: N8N_ENCRYPTION_KEY
