apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-postgres-data
  labels:
    app: forgejo-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
