apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps.yaml
  - cert-manager.yaml
  - eso-namespace.yaml
  - excalidraw.yaml
  - excalidash-test.yaml
  - metallb-system.yaml
  - observability.yaml
  - platform.yaml
