apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  labels:
    app.kubernetes.io/name: calibre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-library
  labels:
    app.kubernetes.io/name: calibre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
