# Documentation only. Do not add this file to kustomization.yaml or commit values.
apiVersion: v1
kind: Secret
metadata:
  name: calibre-secret
type: Opaque
stringData:
  CALIBRE_USERNAME: ""
  CALIBRE_PASSWORD: ""
