apiVersion: v1
kind: Service
metadata:
  name: calibre
  labels:
    app.kubernetes.io/name: calibre
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: calibre
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
