apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: excalidash-backend-secrets
  namespace: excalidash-test
spec:
  data:
    - remoteRef:
        key: secret/apps/apps/excalidash
        property: JWT_SECRET
      secretKey: JWT_SECRET

    - remoteRef:
        key: secret/apps/apps/excalidash
        property: CSRF_SECRET
      secretKey: CSRF_SECRET

  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao

  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: excalidash-backend-secrets
