apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: termix-data
  labels:
    app.kubernetes.io/name: termix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
