apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
        - name: adguard-home
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 53
              protocol: UDP
              name: dns-udp
            - containerPort: 53
              protocol: TCP
              name: dns-tcp
            - containerPort: 3000
              protocol: TCP
              name: setup
            - containerPort: 80
              protocol: TCP
              name: web
          volumeMounts:
            - name: work
              mountPath: /opt/adguardhome/work
            - name: conf
              mountPath: /opt/adguardhome/conf
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: adguard-work
        - name: conf
          persistentVolumeClaim:
            claimName: adguard-conf
