server:
  enabled: true

  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: /openbao/data
    accessMode: ReadWriteOnce

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address         = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_disable     = 1
      }

      storage "file" {
        path = "/openbao/data"
      }

  dev:
    enabled: false

  ha:
    enabled: false

ui:
  enabled: true

injector:
  enabled: true
