apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - namespaces.yaml
  - bootstrap-secrets.yaml
  - controllers.yaml
  - infrastructure.yaml
  - apps.yaml
  - observability-controllers.yaml
  - observability-configs.yaml
