apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-postgres-data
  labels:
    app.kubernetes.io/name: wallabag-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
