apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-images
  labels:
    app.kubernetes.io/name: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
