apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secret
  namespace: apps-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: linkding-secret
    creationPolicy: Owner
  data:
    - secretKey: LD_SUPERUSER_NAME
      remoteRef:
        key: secret/apps/apps-staging/linkding
        property: LD_SUPERUSER_NAME
    - secretKey: LD_SUPERUSER_PASSWORD
      remoteRef:
        key: secret/apps/apps-staging/linkding
        property: LD_SUPERUSER_PASSWORD
