apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidash-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidash-frontend
  template:
    metadata:
      labels:
        app: excalidash-frontend
    spec:
      containers:
        - name: frontend
          image: zimengxiong/excalidash-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: BACKEND_URL
              value: "excalidash-backend.excalidash-test.svc.cluster.local:8000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi



