apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recipes-secret
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: recipes-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: apps/recipes
        property: SECRET_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: apps/recipes
        property: DATABASE_URL
