apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firecrawl-nuq-postgres-pvc
  labels:
    app: firecrawl-nuq-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
