apiVersion: apps/v1
kind: Deployment
metadata:
  name: firecrawl-playwright
  labels:
    app: firecrawl-playwright
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firecrawl-playwright
  template:
    metadata:
      labels:
        app: firecrawl-playwright
    spec:
      containers:
        - name: playwright-service
          image: ghcr.io/firecrawl/playwright-service:linux-amd64@sha256:bd504f4f1068bbba36599bea38f4971d4d2e6b09a030a8b19baf0021ddbaedbc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: firecrawl-playwright-config
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
