apiVersion: v1
kind: Service
metadata:
  name: firecrawl-playwright
spec:
  type: ClusterIP
  selector:
    app: firecrawl-playwright
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
